### ISSUE TITLE
Searching for the Sources/Settings for the CV_LaserModul of the Ender-3S1

### ISSUE THREAD

**Issue by Cyrelion** [CrealityOfficial/Ender-3S1#1]
Hi Team,

I'm searching for the configuration and configuration_adv for the Ender-3S1 with the attached official CV_LaserModul, could you point me to the right direction where this repository is located or what settings I need to set?

Thank you in advanced,
Cyrelion!

**Comment by Creality-mandy** [comment]
You can find it in the Ender 3S1 branch.

**Comment by Nbrooks639** [comment]
searching for how to enable the lcd neopixel or led control menu
