### ISSUE TITLE
Link to Youtube is broken

### ISSUE THREAD

**Issue by ma261065** [CrealityOfficial/Ender-3S1#10]
The link to the YouTube which shows how to upgrade the firmware says "This video has been removed"

**Comment by theSt33v** [comment]
https://www.youtube.com/watch?v=NmoRRFW4zTc

**Comment by ma261065** [comment]
Can you update the readme.md to match please?

**Comment by Creality-mandy** [comment]
> Can you update the readme.md to match please?

Ok, no problem.
