### ISSUE TITLE
Ender 3 S1 Pro with CR-FDM-v2.5.S1_100

### ISSUE THREAD

**Issue by JAlexoid** [CrealityOfficial/Ender-3S1#11]
I have an unexpected mix of hardware. Instead of HW Ver v2.4.S1_301, I have v2.5.S1_100.

How do I build firmware for my equipment?

I am not alone and you can see someone else having the same mismatch (there is a photo with a different HW version)
https://3dprintbeginner.com/creality-ender-3-s1-pro-review/

**Comment by leberschnitzel** [comment]
I have the same HW Version, and for me it meant (same as the reviewer says in your link) that it's a STM32F103 chip. From support: You have to change the platformio.ini and use the F103 envs:
```
default_envs = STM32F103RET6_creality
```
