### ISSUE TITLE
Ender-3 S1 Pro Firmware HOST_ACTION_COMMANDS

### ISSUE THREAD

**Issue by wassereimer86** [CrealityOfficial/Ender-3S1#12]
I am using Ender-3S1_Pro_HWv24S1_301_SWV2.0.8.24F4_F401_FDM_LASER from 3 Aug. 2022. HOST_ACTION_COMMANDS are not enabled. Is it possible to get the current firmware with enabled HOST_ACTION_COMMANDS? My mail is jens@wassereimer.de. Please enable them in future releases!

Sadly there is no repository for the Ender-3 S1 Pro and i can´t find the current and complete (!) configs for the printer to compile a firmware by myself. As in #4 i can´t just use the S1 version. Also they are older than the newest firmware from 3 Aug.

**Comment by mdlopresti** [comment]
I would also like this, PR attached that should enable it the next time a firmware is built

**Comment by CrealityTech** [comment]
this firmware has merged

**Comment by motiregev** [comment]
@CrealityTech  I download the last version from https://www.creality.com/pages/download-ender-3-s1-pro  which is Ender-3 S1_Pro_HWv24S1_301_SWV2.0.8.24F4_FDM_LASER  as it say in the site but the actual version in the bin file is: 3s1pro_hw24s1_301_V2.0.8.16F1_F103_LASER_FDM.bin (it was relaesed in 29-11-2022).
1. It seems to be mismatch in the version between the site and the the inner bin file).
2. In this version the HOST_ACTION_COMMANDS are stil disabled.
When will we have a version that include it for Ender-3 S1 Pro?

**Comment by trapper-** [comment]
I'm also waiting for this release, thanks!
