### ISSUE TITLE
Ender 3 S1 plus

### ISSUE THREAD

**Issue by AntsSymphonie** [CrealityOfficial/Ender-3S1#18]
Where can I find the source code for this printer? Is there a firmware version that allows 300°C with upgraded pro hotend?

**Comment by CrealityTech** [comment]
> 

use this branch and change exturder temp to 300 ,compile it

**Comment by AntsSymphonie** [comment]
This doesn't work. The S1 plus has the same Touch display as the s1 pro which doesn't work with the s1 firmware
