### ISSUE TITLE
Resume print not working

### ISSUE THREAD

**Issue by lin-ycv** [CrealityOfficial/Ender-3S1#28]
Had a filament run out over night, in the morning fed new filament, pressed resume, it purged, but didn't resume printing.

**Comment by kamoteshake** [comment]
which firmware and printer were you using?

**Comment by lin-ycv** [comment]
2.0.8.15F4
![20221130_162314](https://user-images.githubusercontent.com/60565737/204746228-43358a8c-8e73-4c0d-a32e-a36eb0c3fec1.jpg)

**Comment by kamoteshake** [comment]
Hello. sorry it took a while. I just tested this. Started a print then I cut the filament. After the printer detected the filament "ran out", I loaded new filament. It waited to go up the temp and then it started to prime the nozzle. It then continued printing. 

I have an Ender 3S1 Plus and my firmware is 2.0.8.23F4. I see that the latest firmware for S1 Pro is 2.0.8.24F. maybe try updating it?

**Comment by lin-ycv** [comment]
I'm not sure what is issue was, I just tested it, and it also works fine.
does the matter how long it was idle for? or maybe i miss click something...

Which website should I get the update from? There's a bunch of "Creality" websites offering firmware, are they all the same?

**Comment by kamoteshake** [comment]
hahaha yeah. trust me it took me a while to find a good one. I had to contact customer support and they pointed me to the [creality cloud](https://www.crealitycloud.com/software-firmware/firmware?type=2)
