### ISSUE TITLE
[BUG] Watchdog reset when the UBL mesh saved into the EEPROM

### ISSUE THREAD

**Issue by Pethical** [CrealityOfficial/Ender-3S1#32]
Ender 3 S1 pro, latest firmware.

To reproduce run the following gcode:
```
G28
G29
G29 S0
```
At the G29 S0 (save mesh to eeprom) the watchdog timer resets the machine.

**Comment by Pethical** [comment]
The same issue fixed in Marlin 2 years ago...
https://github.com/MarlinFirmware/Marlin/issues/10009

**Comment by kamoteshake** [comment]
have you tried the fix that they recommended from that thread?
