### ISSUE TITLE
Allow to change GRID_MAX_POINTS_X

### ISSUE THREAD

**Issue by Pethical** [CrealityOfficial/Ender-3S1#33]
Ender 3 S1 pro. The supplied bed is warped. Please replace this constant with a variable and allow to change it from menu.
(If you publish the source code and don't violate GPL, then this feature request is not problem, after this we can change ourself. This is the best scenario)

**Comment by rocket59** [comment]
I too would like to change this as the S1 plus has such a large bed.

**Comment by Pethical** [comment]
Source opened, thanks
