### ISSUE TITLE
Cannot Flash STM32F4 Ender 3 S1 Boards

### ISSUE THREAD

**Issue by houseofbugs** [CrealityOfficial/Ender-3S1#8]
I just received a bunch of Ender 3 S1 boards with the F4 CPUs and NONE of them will take firmware at all. I've tried the code here as well as 3rd party code, none of them will flash.

Please let us know what the proper method to flash these boards with the F4 CPU should be because none of the ones I have will take any firmware updates over SD.

Working firmware is here: https://www.th3dstudio.com/hc/downloads/unified-2-firmware/creality/creality-boards-creality/creality-ender-3-s1-firmware-v2415_301-board/

**Comment by houseofbugs** [comment]
[
![20220419_130307](https://user-images.githubusercontent.com/25088191/164124153-38e109f3-4e04-4e40-bf29-b4835beec8f3.jpg)
](url)

**Comment by fabiomaticus** [comment]
I have same problem with two Ender 3 S1 with chip F4.
How i do firmware upgrade?

**Comment by theSt33v** [comment]
Try creating a folder on your SD card called STM32F4_UPDATE. Place the firmware.bin file in that folder, then perform the normal flash procedure (power off printer, insert card, power on printer).

**Comment by houseofbugs** [comment]
Yeah it needs to be in the folder STM32F4_UPDATE and named different EVERY time. Firmware.bin will not work as that is what they used at the factory and its stored in the CPU memory. I have working firmware posted here: https://www.th3dstudio.com/hc/downloads/unified-2-firmware/creality/creality-boards-creality/creality-ender-3-s1-firmware-v2415_301-board/
